### PR TITLE
Mention Accessibility Service on the front page

### PR DESCRIPTION
**Pull request by Brenex**
Added information on the connection between the dependency of accessibility services and external application's autofill ability, including from password managers (specifically 1Password). This should also be added in the suggestion for overrides page (but I can't propose a change since I am not a contributor.)

### CODE REVIEW

**Comment by yokoffing** [comment]
Hey there. Thank you for taking the time to write this!

>This should also be added in the suggestion for overrides page

What would you add/change for the overrides page? Is this only referencing the pref below?
https://github.com/yokoffing/Betterfox/blob/54d453dec5095965c7d74b3ff29a5918747aa338/Peskyfox.js#L52

**Comment by Brenex** [comment]
Yes, that is the specific preference/config. Since it is included in the default provided user.js, I felt people may benefit from reading about it in https://github.com/yokoffing/Betterfox/issues/87 since it may break external application interfacing with firefox.

**Comment by yokoffing** [comment]
I have updated the overrides sticky:

```
// PREF: restore Accessibility Service
user_pref("accessibility.force_disabled", 0);
```

I'm reviewing your description for the `README`. You mention that disabling accessibility service "impact your ability to use a keyboard shortcut to fill in forms including logins", but this would also include screen readers too, yes? If so, I propose the following:

> If you use any of the features below, please view the [common overrides](https://github.com/yokoffing/Betterfox/issues/87) sticky to restore functionality.
> ...
> * **Accessibility Service** is disabled to improve resource utilization and security. This will impact the abilities of external application autofill capability (the ability to use a keyboard shortcut to fill in forms including logins) and screen readers.

**Comment by Brenex** [comment]
Looks great. Thanks for looking at this.

**Pull request merged**
