### PR TITLE
Added installer.py

### PR DESCRIPTION
**Pull request by Denperidge**
Hi! Sorry I didn't make it in time for the latest release, but here is a first proper draft of an installer!
- Allows overrides to be added from a different file
- Automatic default profile backup, that can be disabled if wanted
- The firefox version is automatically determined and used to fetch the latest Betterfox release that has compatibility noted in their release
- Allows installing a specific Betterfox release
- Compatible with any forks people might have, but as of now only as long as they use releases too.

What should be noted:
- MacOS has not been tested, due to a lack of MacOS to test on
- ~~The compile for windows instructions should be expanded to clarify it only compiles for Windows when compiled on Windows, and change the cleanup commands to not use git bash. I'll do this later~~

This should hopefully create a one-click install for most users, whilst allowing advanced users to override any specifics

Instructions for creating a Windows exe are included. This has been tested in Windows 10 and NixOS 24.05 (Python 3.11).

Related: #167, #313

### CODE REVIEW

**Comment by Denperidge** [comment]
OH! If you (@yokoffing) could check the TODO markers. They are about the unclear compatibility of some of the patch releases :relieved:

**Comment by yokoffing** [comment]
Thanks Denperidge! I'll post for feedback on the 130 release.

**Comment by yokoffing** [comment]
Apologies. It's a very busy season of life.

I was looking over the `TODO`:
* The fix in `v.122.1` applied to previous versions too. I called it `.1` because I didn't want to wait to release until `v.123`, but it would apply to versions as far back as `v.107`. So not applicable here, if I'm understanding everything correctly.
* `v.116` and `v.107` look correct.
* As time goes on, we can probably remove those exceptions... It may already be safe to :man_shrugging:

**Comment by Denperidge** [comment]
Absolutely no problem! Very understandable, and I ended up taking a second to update the PR either way. But here we go!

**Comment by yokoffing** [comment]
Merged. @Denperidge, I've added a place for questions and feedback in https://github.com/yokoffing/Betterfox/discussions/337.

**Comment by Denperidge** [comment]
Thank you so much too, and feel free to give me a ping on any improvements you’d like down the road! Will keep an eye on the discussion 😌

**Pull request merged**
